"""Update db

Revision ID: 12cab70df144
Revises: ffbe0e2aeed2
Create Date: 2026-06-07 13:44:21.784122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cab70df144'
down_revision: Union[str, Sequence[str], None] = 'ffbe0e2aeed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pressaoArterial', sa.String(length=20), nullable=False),
    sa.Column('frequencia_cardiaca', sa.Integer(), nullable=False),
    sa.Column('nivel_oxigenacao', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('sintomas', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro')
    # ### end Alembic commands ###
